apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webgoat-devsecops
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/lukaradenkovic2003/webgoat-helm.git'
    targetRevision: HEAD
    path: '.'
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: "ingress.cloudflareSecret"
          value: "vbUHBNf0ClqjpuaUtIIk2m7HEok7RYXU"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: webgoat
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true