image:
  repository: 981207388642.dkr.ecr.us-east-1.amazonaws.com/webgoat-devsecops-app
  tag: "b05a258e0133c75101b9e8ae68dd4e08d6447e96"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ecr-secret

replicaCount: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

ingress:
  host: webgoat-devsecops.xyz
  cloudflareSecret: "secret123"