apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Chart.Name }}-zap-scan
  labels:
    app: {{ .Chart.Name }}-zap
  annotations:
    # Helm hook osigurava da se job pokrene TEK NAKON što su Deployment i Service uspešno kreirani/ažurirani
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  ttlSecondsAfterFinished: 3600 # Briše završeni job nakon 1 sata
  template:
    metadata:
      name: {{ .Chart.Name }}-zap-scan
    spec:
      restartPolicy: Never
      containers:
        - name: zap-baseline-scan
          image: ghcr.io/zaproxy/zaproxy:stable
          command: ["sh", "-c"]
          # ZAP čeka par sekundi da WebGoat bude spreman, pa pokreće Baseline Scan nad internom Service adresom
          args:
            - |
              echo "Čekam da WebGoat servis postane dostupan..."
              sleep 15
              echo "Pokrećem OWASP ZAP DAST skeniranje nad http://{{ .Chart.Name }}:8080/WebGoat ..."
              zap-baseline.py -t http://{{ .Chart.Name }}:8080/WebGoat -I